### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by gulaandrij**
fix php7.2

### CODE REVIEW

**Comment by Zorato** [comment]
Could you please provide more details on how this helps to use php 7.2? I have checked the [spomky-labs/jose v6.1.7](https://github.com/Spomky-Labs/jose/blob/108bde90e676cc45f079f958bae9b75ac9bc1788/composer.json#L28) requirements, and it has php `^5.6|^7.0`.

**Comment by gulaandrij** [comment]
spomky-labs/jose v6.1.7 has dependent "mdanter/ecc": "0.4.*" which has generate error on php 7.2

>  Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Cannot use FG\ASN1\Object as Object because 'Object' is a special class name" at /var/www/git-symfony/vendor/mdanter/ecc/src/Serializer/PrivateKey/DerPrivateKeySerializer.php line 5 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Cannot use FG\\ASN1\\Object as Object because 'Object' is a special class name at /var/www/git-symfony/vendor/mdanter/ecc/src/Serializer/PrivateKey/DerPrivateKeySerializer.php:5)"}

**Comment by gulaandrij** [comment]
"mdanter/ecc": "0.4.*"
https://github.com/phpecc/phpecc/blob/0.4/src/Serializer/PrivateKey/DerPrivateKeySerializer.php#L5

"mdanter/ecc": "0.5.*"
https://github.com/phpecc/phpecc/blob/master/src/Serializer/PrivateKey/DerPrivateKeySerializer.php#L6

**Comment by gulaandrij** [comment]
ping @Zorato

**Comment by cheelahim** [comment]
Hey @gulaandrij. We have planned to drop supporting PHP 5.6 this year, but we would like too keep for at least couple of months. May be we could change it to  `"spomky-labs/jose": "^6.1|^7.0"` to keep compatibility. If it works for you update the PR and I will merge it and release.

**Comment by gulaandrij** [comment]
done

**Comment by cheelahim** [comment]
Thank you for contribution @gulaandrij. Feel free to report any issues.

**Pull request merged**
